### ISSUE TITLE
get Coordinates

### ISSUE THREAD

**Issue by awenznero** [dallin-christensen/react-img-markdown#5]
Thanks for your work!
is there an easy way to obtain the coordinates of drawn rects?

**Comment by dallin-christensen** [comment]
Hello @awenznero, there is not an officially supported way to access the paths created by the user, I will create a ticket to expose the `paths` object to devs and hopefully get that in soon.

If you're using the hooks API and looking for a workaround in the meantime, you can actually access that `paths` object through the `bind` property like this, though it is not officially supported.

```
const { bind } = useImgMarkup()

const paths = bind.paths
```

From there you can drill down into the data for each path. If you're using the RenderProps version of the API, I do not believe there is a workaround to get to that data. For now, that `bind` property is the only way, until I can get around to returning the paths object at the top level.

**Comment by awenznero** [comment]
Thanks for the quick reply. Your workaround helped me, thanks for that! It's nice to see that the project is active, it's as simple and effective as I need it to be, other tools like this are often overloaded or not further maintained.

Keep up the good work

**Comment by dallin-christensen** [comment]
Thanks @awenznero! I appreciate it. Glad to hear that the workaround worked for you!
